namespace: fredwangwang
name: log_sanitize
version: 1.0.1

readme: README.md

authors:
- Huan Wang

description: Log sanitize callback plugin with controling module to adding more santiizing keywords during runtime.

license:
- Apache-2.0

# A list of tags you want to associate with the collection for indexing/searching. A tag name has the same character
# requirements as 'namespace' and 'name'
tags: ['plugin', 'callback', 'sanitize']

# Collections that this collection requires to be installed for it to be usable. The key of the dict is the
# collection label 'namespace.name'. The value is a version range
# L(specifiers,https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification). Multiple version
# range specifiers can be set and are separated by ','
dependencies: {}

build_ignore:
- tests
- demo.yml
- ansible.cfg

repository: https://github.com/fredwangwang/ansible-log-sanitize
issues: https://github.com/fredwangwang/ansible-log-sanitize/issues
documentation: https://github.com/fredwangwang/ansible-log-sanitize
homepage: https://github.com/fredwangwang/ansible-log-sanitize
